  version: '3'
  services:
    gateway:
      image: samuel19982/gateway:latest
      ports:
        - "80:8000"
      environment:
        - REDIS_URL=redis://cache:6379
        - BASE_URL=<your-livsi-url>
        - PASSWORD=<your-livisi-password>
        - USERNAME=<your-livisi-username>
        # BASIC_AUTH=true
        # BASIC_USERNAME=<your-basic-auth-username>
        # BASIC_PASSWORD=<your-basic-auth-password>
        # OIDC_CLIENT_ID=<your-oidc-client-id>

      depends_on:
        - cache
    cache:
      image: redis:7.0.11
      restart: always
      command: redis-server --save 20 1 --loglevel warning
      volumes:
        - cache:/data