version: '3'
services:
    gateway:
      image: samuel19982/gateway:latest
      ports:
        - "80:8000"
      environment:
        - REDIS_URL=redis://cache:6379
        - BASE_URL=<your-base-url>
        - BASIC_AUTH=true
        - PASSWORD=<livisi-password>
        - USERNAME=<livisi-username>
        - BASIC_USERNAME=<login-username>
        - BASIC_PASSWORD=<login-password>
        # BASIC_AUTH=true
        # BASIC_USERNAME=<your-basic-auth-username>
        # BASIC_PASSWORD=<your-basic-auth-password>
        # OIDC_CLIENT_ID=<your-oidc-client-id>

      depends_on:
        - cache
    cache:
      image: redis:7.0.11
      ports:
        - "6379:6379"
      restart: always
      command: redis-server --save 20 1 --loglevel warning
      volumes:
        - cache:/data
volumes:
  cache: