version: '3'
services:
    gateway:
      image: samuel19982/gateway:latest
      ports:
        - "80:8000"
      environment:
        - REDIS_URL=redis://192.168.2.50:6379
        - BASE_URL=http://192.168.1.120:8080
        - BASIC_AUTH=true
        - PASSWORD=AVAQKHqq#e4vssCFLW6FSTG*cm57%!
        - USERNAME=admin
        - BASIC_USERNAME=test
        - BASIC_PASSWORD=test
        # BASIC_AUTH=true
        # BASIC_USERNAME=<your-basic-auth-username>
        # BASIC_PASSWORD=<your-basic-auth-password>
        # OIDC_CLIENT_ID=<your-oidc-client-id>

      depends_on:
        - cache
    cache:
      image: redis:7.0.11
      ports:
        - "6379:6379"
      restart: always
      command: redis-server --save 20 1 --loglevel warning
      volumes:
        - cache:/data
volumes:
  cache: