version: '3'
services:
    gateway:
      image: samuel19982/gateway:latest
      volumes:
        - "./db:/app/db"
      ports:
        - "80:8000"
      environment:
        - BASE_URL=<your-base-url>
        - AUTH_MODE=none
        - PASSWORD=<livisi-password>
        - USERNAME=<livisi-username>
        # AUTH_MODE=basic
        # BASIC_USERNAME=<your-basic-auth-username>
        # BASIC_PASSWORD=<your-basic-auth-password>
        # AUTH_MODE=oidc
        # OIDC_CLIENT_ID=<your-oidc-client-id>
        # OIDC_REDIRECT_URI=<http(s)://your-host/ui/>
        # OIDC_SCOPE=openid profile email
        # OIDC_AUTHORITY=<https://keycloak-or-authelia-authority>
        # OIDC_AUDIENCE=<optional-audience-override>
