version: '3'
services:
    gateway:
      image: samuel19982/gateway:latest
      volumes:
        - "./db:/app/db"
      ports:
        - "80:8000"
      environment:
        - BASE_URL=<your-base-url>
        - BASIC_AUTH=true
        - PASSWORD=<livisi-password>
        - USERNAME=<livisi-username>
        - BASIC_USERNAME=<login-username>
        - BASIC_PASSWORD=<login-password>
        # BASIC_AUTH=true
        # BASIC_USERNAME=<your-basic-auth-username>
        # BASIC_PASSWORD=<your-basic-auth-password>
        # OIDC_CLIENT_ID=<your-oidc-client-id>