/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_all_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_server_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/capability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_capability_history_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_email_settings_doc"];
        put: operations["put_email_settings_doc"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_email_test_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_interactions_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_interaction_doc"];
        put: operations["put_interaction_doc"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/{id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trigger_interaction_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_locations_doc"];
        put?: never;
        post: operations["post_location_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_location_doc"];
        put: operations["put_location_doc"];
        post?: never;
        delete: operations["delete_location_doc"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_messages_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/message/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_message_doc"];
        put: operations["put_message_doc"];
        post?: never;
        delete: operations["delete_message_doc"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_product_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/hash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_product_hash_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentry/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sentry_settings_doc"];
        put: operations["put_sentry_settings_doc"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentry/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_sentry_test_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service/sun-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sun_times_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unmount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["unmount_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usb_storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_usb_storage_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiServerConfigDoc: {
            authMode: components["schemas"]["AuthModeDoc"];
            basicAuth: boolean;
            oidcConfig?: null | components["schemas"]["OidcConfigDoc"];
            oidcConfigured: boolean;
        };
        /** @enum {string} */
        AuthModeDoc: "none" | "basic" | "oidc";
        CapabilityHistoryDoc: {
            dataName: string;
            dataValue: string;
            entityId: string;
            eventTime: string;
            eventType: string;
        };
        EmailSettingsDoc: {
            email_password: string;
            email_username: string;
            notification_device_low_battery: boolean;
            notifications_device_unreachable: boolean;
            recipient_list: string[];
            server_address: string;
            /** Format: int32 */
            server_port_number: number;
        };
        EmailTestDoc: {
            result: string;
        };
        HashDoc: {
            hash: string;
        };
        LocationDoc: {
            config: unknown;
            devices?: string[] | null;
            id: string;
            tags?: unknown;
        };
        MessagePropertiesDoc: {
            changeReason?: string | null;
            deviceLocation?: string | null;
            deviceName?: string | null;
            deviceSerial?: string | null;
            /** Format: int32 */
            expiresAfterMinutes?: number | null;
            namespace?: string | null;
            read?: boolean | null;
            requesterInfo?: string | null;
            shcRemoteRebootReason?: string | null;
            timestamp?: string | null;
        };
        MessageReadDoc: {
            read: boolean;
        };
        MessageResponseDoc: {
            capabilities?: string[] | null;
            class?: string | null;
            devices?: string[] | null;
            id: string;
            messages?: string[] | null;
            namespace?: string | null;
            properties?: null | components["schemas"]["MessagePropertiesDoc"];
            read: boolean;
            timestamp: string;
            type: string;
        };
        NotificationProviderConfigDoc: (components["schemas"]["TelegramProviderConfigDoc"] & {
            /** @enum {string} */
            kind: "telegram";
        }) | (components["schemas"]["WebhookProviderConfigDoc"] & {
            /** @enum {string} */
            kind: "webhook";
        });
        OidcConfigDoc: {
            authority: string;
            clientId: string;
            redirectUri: string;
            scope: string;
        };
        ProductDoc: {
            config?: unknown;
            generic?: boolean | null;
            id: string;
            provisioned?: boolean | null;
            state?: unknown;
            type: string;
            version?: string | null;
        };
        SentrySettingsDoc: {
            enabled: boolean;
            monitored_device_ids: string[];
            provider: components["schemas"]["NotificationProviderConfigDoc"];
        };
        SentryTestDoc: {
            result: string;
        };
        SunTimesDoc: {
            geoLocation: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            nextEventAt?: string | null;
            nextEventName?: string | null;
            nextSunrise?: string | null;
            nextSunset?: string | null;
            sunrise?: string | null;
            sunset?: string | null;
        };
        TelegramProviderConfigDoc: {
            bot_token: string;
            chat_id: string;
            /** Format: int64 */
            message_thread_id?: number | null;
        };
        UsbStorageDoc: {
            external_storage: boolean;
        };
        WebhookProviderConfigDoc: {
            bearer_token: string;
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_all_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All aggregated API data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_api_server_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiServerConfigDoc"];
                };
            };
        };
    };
    get_capability_history_doc: {
        parameters: {
            query: {
                /** @description Entity id with capability suffix */
                entityId: string;
                /** @description Start timestamp ISO-8601 */
                start: string;
                /** @description End timestamp ISO-8601 */
                end: string;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                pagesize?: number;
                /** @description Event type */
                eventType?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityHistoryDoc"][];
                };
            };
        };
    };
    get_email_settings_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSettingsDoc"];
                };
            };
        };
    };
    put_email_settings_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSettingsDoc"];
            };
        };
        responses: {
            /** @description Email settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_email_test_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailTestDoc"];
                };
            };
        };
    };
    get_interactions_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_interaction_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interaction id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single interaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    put_interaction_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interaction id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Updated interaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_interaction_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interaction id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trigger result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_locations_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationDoc"][];
                };
            };
        };
    };
    post_location_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationDoc"];
            };
        };
        responses: {
            /** @description Location created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationDoc"];
                };
            };
        };
    };
    get_location_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationDoc"];
                };
            };
        };
    };
    put_location_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationDoc"];
            };
        };
        responses: {
            /** @description Location updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationDoc"];
                };
            };
        };
    };
    delete_location_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationDoc"];
                };
            };
        };
    };
    get_messages_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDoc"][];
                };
            };
        };
    };
    get_message_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Message id */
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDoc"];
                };
            };
        };
    };
    put_message_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Message id */
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageReadDoc"];
            };
        };
        responses: {
            /** @description Message updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDoc"];
                };
            };
        };
    };
    delete_message_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Message id */
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_product_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installed products/drivers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDoc"][];
                };
            };
        };
    };
    get_product_hash_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product hash */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HashDoc"];
                };
            };
        };
    };
    get_sentry_settings_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sentry settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentrySettingsDoc"];
                };
            };
        };
    };
    put_sentry_settings_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SentrySettingsDoc"];
            };
        };
        responses: {
            /** @description Sentry settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentrySettingsDoc"];
                };
            };
        };
    };
    post_sentry_test_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sentry notification test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentryTestDoc"];
                };
            };
        };
    };
    get_sun_times_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sunrise / sunset times */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SunTimesDoc"];
                };
            };
        };
    };
    get_status_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    unmount_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description USB unmounted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_usb_storage_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description USB storage status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsbStorageDoc"];
                };
            };
        };
    };
}
