on:
  push:


jobs:
  build-expo:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      ANDROID_APPLICATION_ID: "com.samtv12345.smarthome"
    steps:
      - name: install-jdk17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: actions/checkout@v2
      - name: Install Expo CLI
        run: npm install -g eas-cli
      - name: Install dependencies
        working-directory: mobile
        run: npm install
      - name: Build
        working-directory: mobile
        run: eas build --platform android --local
      - name: Rename artifact
        working-directory: mobile
        run: mv *.aab app-release.aab
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: mobile/app-release.aab
          name: android-aab