name: Build release binaries

on:
    push:
        branches:
        - master
        - main

jobs:
  release-windows:
    name: release x86_64-pc-windows-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: "Create frontend"
        run: |
          cd ui-new
          npm install -g pnpm@latest
          pnpm install
          pnpm run build:copy
      - name: Compile
        working-directory: api
        run: |
            sudo apt-get update
            sudo apt-get install -y gcc-multilib mingw-w64 gcc-mingw-w64-x86-64
            rustup target add x86_64-pc-windows-gnu
            cargo build --release --target x86_64-pc-windows-gnu
      - name: Archive
        working-directory: api
        run: |
          mkdir -p dist
          ls -lisa target/x86_64-pc-windows-gnu/release
          mv target/x86_64-pc-windows-gnu/release/api* dist/
          mkdir dist/static
          cp -r static/* dist/static/
          cd dist
          zip -r app-x86_64-pc-windows-gnu.zip .
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
              name: app-x86_64-pc-windows-gnu
